language: python

dist: xenial

python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest -p no:warnings
  - coverage run -m pytest -p no:warnings
  - echo "${PYPIPASS}"

deploy:
  provider: pypi
  user: East_wu
  password:
    secure: ${PYPIPASS}
  skip_cleanup: true
  on:
    python: 3.6
    branch: develop

after_script:
  - coveralls
